export const BREAKPOINT_MOBILE_SMALL = 320;
export const BREAKPOINT_MOBILE_MEDIUM = 375;
export const BREAKPOINT_MOBILE_LARGE = 425;

export const BREAKPOINT_TABLET = 768;

export const BREAKPOINT_DESKTOP_MEDIUM = 1024;
export const BREAKPOINT_DESKTOP_LARGE = 1440 + 100;
export const BREAKPOINT_DESKTOP_HUGE = 2560;